CREATE TABLE IF NOT EXISTS public.admin_team_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  environment text NOT NULL CHECK (environment IN ('production', 'preview')),
  coach_id integer NOT NULL,
  coach_name text NOT NULL,
  admin_user_id uuid NOT NULL,
  admin_email text NOT NULL,
  action text NOT NULL CHECK (action IN ('submit_team_on_behalf')),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_team_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read team audit log"
ON public.admin_team_audit_log FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
      AND profiles.environment = admin_team_audit_log.environment
  )
);

CREATE POLICY "Admins can insert team audit log"
ON public.admin_team_audit_log FOR INSERT TO authenticated
WITH CHECK (
  admin_user_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
      AND profiles.environment = admin_team_audit_log.environment
  )
);

CREATE INDEX IF NOT EXISTS admin_team_audit_log_environment_coach_created_idx
ON public.admin_team_audit_log (environment, coach_id, created_at DESC);
