-- Batch 2: durable season identity, immutable closeout records, and write locks.
-- This migration is additive and backfills all existing competition data to 2026.

CREATE TABLE IF NOT EXISTS public.competition_seasons (
  environment text NOT NULL CHECK (environment IN ('production', 'preview')),
  season_year integer NOT NULL CHECK (season_year BETWEEN 2000 AND 2100),
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'completed', 'archived')),
  started_at timestamptz,
  completed_at timestamptz,
  archived_at timestamptz,
  locked_at timestamptz,
  premier_coach_id integer,
  premier_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (environment, season_year),
  CHECK (status NOT IN ('completed', 'archived') OR locked_at IS NOT NULL),
  CHECK (status <> 'archived' OR archived_at IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS competition_seasons_one_active_per_environment
ON public.competition_seasons (environment)
WHERE status = 'active';

CREATE TABLE IF NOT EXISTS public.season_archives (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  environment text NOT NULL CHECK (environment IN ('production', 'preview')),
  season_year integer NOT NULL CHECK (season_year BETWEEN 2000 AND 2100),
  archive_version integer NOT NULL DEFAULT 1 CHECK (archive_version > 0),
  payload jsonb NOT NULL,
  source_row_counts jsonb NOT NULL,
  checksum text NOT NULL CHECK (length(btrim(checksum)) >= 32),
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (environment, season_year, archive_version),
  FOREIGN KEY (environment, season_year)
    REFERENCES public.competition_seasons (environment, season_year)
);

ALTER TABLE public.competition_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_archives ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read seasons" ON public.competition_seasons;
CREATE POLICY "Authenticated users can read seasons"
ON public.competition_seasons FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Authenticated users can read season archives" ON public.season_archives;
CREATE POLICY "Authenticated users can read season archives"
ON public.season_archives FOR SELECT TO authenticated USING (true);

ALTER TABLE public.app_settings
  ADD COLUMN IF NOT EXISTS season_year integer;
UPDATE public.app_settings SET season_year = 2026 WHERE season_year IS NULL;
ALTER TABLE public.app_settings
  ALTER COLUMN season_year SET DEFAULT 2026,
  ALTER COLUMN season_year SET NOT NULL;

INSERT INTO public.competition_seasons (
  environment, season_year, status, started_at, created_at, updated_at
)
SELECT environment, 2026, 'active', now(), now(), now()
FROM public.app_settings
WHERE environment IN ('production', 'preview')
ON CONFLICT (environment, season_year) DO NOTHING;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'super8_match_results',
    'season_fixture',
    'round_submissions',
    'coach_team_selections',
    'afl_player_round_stats',
    'afl_matches',
    'afl_round_finalisation',
    'weekly_team_lists',
    'admin_team_audit_log',
    'super8_ladder_snapshots'
  ]
  LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format(
        'ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS season_year integer',
        table_name
      );
      EXECUTE format(
        'UPDATE public.%I SET season_year = 2026 WHERE season_year IS NULL',
        table_name
      );
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN season_year SET DEFAULT 2026',
        table_name
      );
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN season_year SET NOT NULL',
        table_name
      );
      EXECUTE format(
        'ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I',
        table_name,
        table_name || '_season_year_check'
      );
      EXECUTE format(
        'ALTER TABLE public.%I ADD CONSTRAINT %I CHECK (season_year BETWEEN 2000 AND 2100)',
        table_name,
        table_name || '_season_year_check'
      );
    END IF;
  END LOOP;
END
$$;

-- super8_match_results historically had neither environment nor season.
ALTER TABLE public.super8_match_results
  ADD COLUMN IF NOT EXISTS environment text;
UPDATE public.super8_match_results
SET environment = 'production'
WHERE environment IS NULL;
ALTER TABLE public.super8_match_results
  ALTER COLUMN environment SET DEFAULT 'production',
  ALTER COLUMN environment SET NOT NULL;
ALTER TABLE public.super8_match_results
  DROP CONSTRAINT IF EXISTS super8_match_results_environment_check;
ALTER TABLE public.super8_match_results
  ADD CONSTRAINT super8_match_results_environment_check
  CHECK (environment IN ('production', 'preview'));

-- weekly_team_lists is shared today. Give it an explicit environment before
-- Preview and Production begin staging independent future seasons.
ALTER TABLE public.weekly_team_lists
  ADD COLUMN IF NOT EXISTS environment text;
UPDATE public.weekly_team_lists
SET environment = 'production'
WHERE environment IS NULL;
ALTER TABLE public.weekly_team_lists
  ALTER COLUMN environment SET DEFAULT 'production',
  ALTER COLUMN environment SET NOT NULL;
ALTER TABLE public.weekly_team_lists
  DROP CONSTRAINT IF EXISTS weekly_team_lists_environment_check;
ALTER TABLE public.weekly_team_lists
  ADD CONSTRAINT weekly_team_lists_environment_check
  CHECK (environment IN ('production', 'preview'));

-- Add new season-aware indexes alongside the legacy constraints. Legacy keys
-- remain until every application writer has moved to the new conflict target.
CREATE UNIQUE INDEX IF NOT EXISTS super8_match_results_season_match_key
ON public.super8_match_results
  (environment, season_year, round_number, matchup_index);

CREATE INDEX IF NOT EXISTS season_fixture_environment_season_round_idx
ON public.season_fixture (environment, season_year, competition_round, matchup_index);

CREATE UNIQUE INDEX IF NOT EXISTS round_submissions_season_coach_round_key
ON public.round_submissions (environment, season_year, coach_id, round_number);

CREATE UNIQUE INDEX IF NOT EXISTS coach_team_selections_season_coach_key
ON public.coach_team_selections (environment, season_year, coach_id);

CREATE UNIQUE INDEX IF NOT EXISTS afl_player_round_stats_season_player_key
ON public.afl_player_round_stats
  (environment, season_year, afl_round, afl_team_code, player_name);

CREATE INDEX IF NOT EXISTS afl_matches_environment_season_round_idx
ON public.afl_matches (environment, season_year, afl_round);

CREATE UNIQUE INDEX IF NOT EXISTS afl_round_finalisation_season_round_key
ON public.afl_round_finalisation (environment, season_year, afl_round);

CREATE INDEX IF NOT EXISTS weekly_team_lists_environment_season_round_idx
ON public.weekly_team_lists (environment, season_year, round);

DO $$
BEGIN
  IF to_regclass('public.super8_ladder_snapshots') IS NOT NULL THEN
    EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS super8_ladder_snapshots_season_team_key ON public.super8_ladder_snapshots (environment, season_year, round_number, team)';
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.reject_locked_season_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  target_environment text;
  target_season_year integer;
  target_status text;
BEGIN
  target_environment := COALESCE(NEW.environment, OLD.environment);
  target_season_year := COALESCE(NEW.season_year, OLD.season_year);

  SELECT status
  INTO target_status
  FROM public.competition_seasons
  WHERE environment = target_environment
    AND season_year = target_season_year;

  IF target_status IN ('completed', 'archived') THEN
    RAISE EXCEPTION 'Season %/% is locked and cannot be changed.',
      target_environment, target_season_year;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'super8_match_results',
    'season_fixture',
    'round_submissions',
    'coach_team_selections',
    'finals_results',
    'afl_player_round_stats',
    'afl_matches',
    'afl_round_finalisation',
    'weekly_team_lists'
  ]
  LOOP
    IF to_regclass('public.' || table_name) IS NOT NULL THEN
      EXECUTE format(
        'DROP TRIGGER IF EXISTS reject_locked_season_write ON public.%I',
        table_name
      );
      EXECUTE format(
        'CREATE TRIGGER reject_locked_season_write BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.reject_locked_season_write()',
        table_name
      );
    END IF;
  END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION public.archive_preview_season(
  p_season_year integer,
  p_payload jsonb,
  p_source_row_counts jsonb,
  p_checksum text,
  p_premier_name text,
  p_confirmation text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  archive_id bigint;
  grand_final_complete boolean;
BEGIN
  IF p_confirmation <> format('ARCHIVE PREVIEW %s', p_season_year) THEN
    RAISE EXCEPTION 'Typed Preview archive confirmation did not match.';
  END IF;
  IF p_payload IS NULL OR p_source_row_counts IS NULL THEN
    RAISE EXCEPTION 'Archive payload and source row counts are required.';
  END IF;
  IF length(btrim(COALESCE(p_checksum, ''))) < 32 THEN
    RAISE EXCEPTION 'A complete archive checksum is required.';
  END IF;
  IF btrim(COALESCE(p_premier_name, '')) = '' THEN
    RAISE EXCEPTION 'The Premiers must be confirmed before archiving.';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.finals_results
    WHERE environment = 'preview'
      AND season_year = p_season_year
      AND match_code = 'GF'
      AND coach_1_score IS NOT NULL
      AND coach_2_score IS NOT NULL
      AND completed_at IS NOT NULL
  ) INTO grand_final_complete;

  IF NOT grand_final_complete THEN
    RAISE EXCEPTION 'The Preview Grand Final is not complete.';
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('archive_preview_season'),
    p_season_year
  );

  INSERT INTO public.season_archives (
    environment, season_year, payload, source_row_counts, checksum, created_by
  ) VALUES (
    'preview', p_season_year, p_payload, p_source_row_counts, p_checksum, auth.uid()
  )
  RETURNING id INTO archive_id;

  UPDATE public.competition_seasons
  SET status = 'archived',
      premier_name = p_premier_name,
      completed_at = COALESCE(completed_at, now()),
      archived_at = now(),
      locked_at = now(),
      updated_at = now()
  WHERE environment = 'preview'
    AND season_year = p_season_year
    AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'The requested Preview season is not active or does not exist.';
  END IF;

  RETURN archive_id;
END;
$$;

REVOKE ALL ON FUNCTION public.archive_preview_season(integer, jsonb, jsonb, text, text, text)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.archive_preview_season(integer, jsonb, jsonb, text, text, text)
TO service_role;
