-- Keep AFL-provider names aligned with the canonical player names used by the app.
-- Aliases are environment-scoped but intentionally season-independent: they
-- describe player identity, so the same mapping can be reused after rollover
-- without rewriting completed historical statistics.

CREATE TABLE IF NOT EXISTS public.afl_player_name_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  environment text NOT NULL CHECK (environment IN ('preview', 'production')),
  afl_name text NOT NULL CHECK (btrim(afl_name) <> ''),
  app_name text NOT NULL CHECK (btrim(app_name) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (environment, afl_name)
);

ALTER TABLE public.afl_player_name_aliases ENABLE ROW LEVEL SECURITY;

INSERT INTO public.afl_player_name_aliases (environment, afl_name, app_name)
VALUES
  ('preview', 'Nicholas Madden', 'Nick Madden'),
  ('production', 'Nicholas Madden', 'Nick Madden')
ON CONFLICT (environment, afl_name) DO UPDATE
SET
  app_name = EXCLUDED.app_name,
  updated_at = now();
